lib/blockchain_events_web/router.ex
defmodule BlockchainEventsWeb.Router do
  use BlockchainEventsWeb, :router
  import Plug.BasicAuth
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admins_only do
    plug :basic_auth, username: "admin", password: "admin"
  end

  scope "/", BlockchainEventsWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/event", EventPageController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlockchainEventsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser, :admins_only]
      live_dashboard "/dashboard", metrics: {BlockchainEventsWeb.Telemetry, :metrics}
    end
  end
end

lib/blockchain_events_web/live/events_listing_live.ex
defmodule BlockchainEventsWeb.EventsListingLive do
  use Phoenix.LiveView
  use Timex
  require Logger

  alias BlockchainEventsWeb.EventsListingView

  def mount(_params, _session, socket) do
    {:ok, data} = Cachex.get(:cache_gss_data, :gss)
    ss_static_data = data |> Enum.reverse()

    sort_options = ["Sort by date", "Sort by new added"]

    socket =
      socket
      |> assign(:ss_static_data, ss_static_data)
      |> assign(:ss_data, ss_static_data)
      |> assign(:applied_filters, :applied_filters)
      |> assign(:sort_options, sort_options)
      |> assign(:events_sort, "Sort by new added")

    {:ok, socket}
  end

  def render(assigns) do
    EventsListingView.render(
      "index.html",
      assigns
    )
  end

  def handle_event("apply_filters", filters, socket) do
    ss_data =
      socket.assigns.ss_static_data
      |> date_filter(filters)
      |> event_type_filter(filters)
      |> blockchain_type_filter(filters)
      |> price_filter(filters)
      |> dev_type_filter(filters)

    {:noreply, assign(socket, :ss_data, ss_data)}
  end

  def handle_event("events_sorting", metadata, socket) do
    events_sort = metadata["sorting"]["sort_option"]
    ss_data = socket.assigns.ss_data

    ss_data =
      case events_sort do
        "Sort by date" -> Enum.sort_by(ss_data, & &1.start_date, {:desc, Date})
        _ -> Enum.sort_by(ss_data, & &1.id, :desc)
      end

    socket =
      socket
      |> assign(:ss_data, ss_data)

    {:noreply, socket}
  end

  def dev_type_filter(pf_data, filters) do
    if Map.has_key?(filters, "dev_type") == true do
      case filters["dev_type"] do
        "junior" -> Enum.filter(pf_data, fn map -> map.dev_type === "junior" end)
        "middle" -> Enum.filter(pf_data, fn map -> map.dev_type === "middle" end)
        "experienced" -> Enum.filter(pf_data, fn map -> map.dev_type === "experienced" end)
        _ -> pf_data
      end
    else
      pf_data
    end
  end

  def price_filter(bc_data, filters) do
    if Map.has_key?(filters, "price") == true do
      case filters["price"] do
        "free" -> Enum.filter(bc_data, fn map -> map.price === false end)
        "paid" -> Enum.filter(bc_data, fn map -> map.price === true end)
        _ -> bc_data
      end
    else
      bc_data
    end
  end

  def blockchain_type_filter(et_data, filters) do
    bc_data =
      Enum.filter(filters, fn {_k, v} -> v === "bc_type" end)
      |> Enum.into(%{})

    if bc_data === %{} || Map.has_key?(bc_data, "all") do
      et_data
    else
      bc_types = Enum.map(bc_data, fn {k, _v} -> k end)

      Enum.filter(et_data, fn map -> map.blockchain in bc_types end)
    end
  end

  def event_type_filter(df_data, filters) do
    et_data =
      Enum.filter(filters, fn {k, v} -> v === "true" end)
      |> Enum.into(%{})

    if et_data === %{} || Map.has_key?(et_data, "all") do
      df_data
    else
      event_types = Enum.map(et_data, fn {k, v} -> k end)
      Enum.filter(df_data, fn map -> map.event_type in event_types end)
    end
  end

  def date_filter(ss_data, filters) do
    if Map.has_key?(filters, "dates") == true do
      today = Timex.today()

      case filters["dates"] do
        "today" ->
          today = Timex.today()
          Enum.filter(ss_data, fn map -> map.start_date === today end)

        "week" ->
          beginning_of_week = Timex.beginning_of_week(today)

          week_interval =
            Timex.Interval.new(
              from: beginning_of_week,
              until: [days: 7],
              left_open: false,
              right_open: true
            )

        "month" ->
          beginning_of_month = Timex.beginning_of_month(today)
          end_of_month = Timex.end_of_month(today)

          month_interval =
            Timex.Interval.new(
              from: beginning_of_month,
              until: end_of_month,
              left_open: false,
              right_open: true
            )

          Enum.filter(ss_data, fn map -> map.start_date in month_interval end)

        "year" ->
          beginning_of_year = Timex.beginning_of_year(today)
          end_of_year = Timex.end_of_year(today)

          year_interval =
            Timex.Interval.new(
              from: beginning_of_year,
              until: end_of_year,
              left_open: false,
              right_open: true
            )

          Enum.filter(ss_data, fn map -> map.start_date in year_interval end)

        _ ->
          ss_data
      end
    else
      ss_data
    end
  end

  def color_label(event_type) do
    colors = %{
      "seminar" => "red",
      "conference" => "blue",
      "forum" => "green",
      "course" => "yellow",
      "summit" => "orange",
      "hackaton" => "purple",
      "other" => "pink"
    }

    colors[event_type]
  end
end

lib/blockchain_events_web/views/events_listing_view.ex
defmodule BlockchainEventsWeb.EventsListingView do
  use BlockchainEventsWeb, :view
end

lib/blockchain_events_web/templates/events_listing/index.html.leex
<div class="wrapper">
  <%= render("sidebar.html", applied_filters: @applied_filters, sort_options: @sort_options, events_sort: @events_sort) %>
  <main role="main"  style="margin-left: 2%; margin-top: 2%">
    <%= if @ss_data === [] do %>
      <h1> No events. Please select other filters or you can add a new event </h1>
    <% else %>
      <div class="row">
        <%= for event <- @ss_data do %>
          <div class="col-sm-12 col-md-12 col-lg-6 event-item">
            <div class="card" style="margin-bottom: 1%; border-left: 6px solid <%= BlockchainEventsWeb.EventsListingLive.color_label(event.event_type) %> ">
              <div class="topright badge-pill" style="background-color: <%= BlockchainEventsWeb.EventsListingLive.color_label(event.event_type) %>"><%= event.event_type %></div>
              <div class="row">
                <div class="col-12 col-md-6 card-img-wrapper" >
                  <img class="card-img-top " src="<%= event.image_url %>"  alt="Card image cap">
                </div>
                <div class="card-body col-12 col-md-6">
                  <h5 class="card-title" style="margin-top: 10%"><%= event.event_name %></h5>
                  <p class="card-text" style="font-size: 10px"><%= event.start_date %></p>
                  <%= link "Read more", class: "bottomright btn btn-outline-secondary", to: Routes.event_page_path(@socket, :show, event.id) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </main>
</div>
</div>

lib/blockchain_events_web/templates/events_listing/sidebar.html.leex
  <nav id="sidebar" class="active">
  <ul class="list-unstyled components">
    <form action="#" phx-submit="apply_filters">
      <li>
        <a href="/">
          <i class="fa fa-calendar"></i>
        </a>
        <span>
          <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" style="font-weight: bold;">Date</a>
          <ul class="collapse list-unstyled" id="pageSubmenu">
            <li>
              <input type="radio" name="dates" value="all" >All dates
            </li>
            <li>
              <input type="radio" name="dates" value="today" >Starts today
            </li>
            <li>
              <input type="radio" name="dates" value="week" >Starts this week
            </li>
            <li>
              <input type="radio" name="dates" value="month" >Starts this month
            </li>
            <li>
              <input type="radio" name="dates" value="year" >Starts this year
            </li>
          </ul>
        </a>
      </span>
    </li>
    <li style="margin-top: 10px">
      <a href="/">
        <i class="fa fa-glass"></i>
      </a>
      <span>
        <a href="#pageSubmenu2" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" style="font-weight: bold;">Event type</a>
        <ul class="collapse list-unstyled" id="pageSubmenu2">
          <li>
            <input type="checkbox" name="all" value="true" >All types
          </li>
          <li>
            <input type="checkbox" name="seminar" value="true" >Seminar
          </li>
          <li>
            <input type="checkbox" name="conference" value="true">Conference
          </li>
          <li>
            <input type="checkbox" name="forum" value="true" >Forum
          </li>
          <li>
            <input type="checkbox" name="course" value="true" >Course
          </li>
          <li>
            <input type="checkbox" name="summit" value="true" >Summit
          </li>
          <li>
            <input type="checkbox" name="hackaton" value="true" >Hackaton
          </li>
          <li>
            <input type="checkbox" name="others" value="true" >Others
          </li>
        </ul>
      </a>
    </span>
  </li>
  <li style="margin-top: 10px">
    <a href="#">
      <i class="fa fa-chain"></i>
    </a>
    <span>
      <a href="#pageSubmenu3" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" style="font-weight: bold;">Blockchain type</a>
      <ul class="collapse list-unstyled" id="pageSubmenu3">
        <li>
          <input type="checkbox" name="all" value="bc_type" >All blockchains
        </li>
        <li>
          <input type="checkbox" name="Bitcoin" value="bc_type" >Bitcoin
        </li>
        <li>
          <input type="checkbox" name="Ethereum" value="bc_type">Ethereum
        </li>
        <li>
          <input type="checkbox" name="Ripple" value="bc_type" >Ripple
        </li>
        <li>
          <input type="checkbox" name="EOS" value="bc_type" >EOS
        </li>
        <li>
          <input type="checkbox" name="Tezos" value="bc_type" >Tezos
        </li>
        <li>
          <input type="checkbox" name="Other" value="bc_type" >Other
        </li>
      </ul>
    </a>
  </span>
</li>
<li style="margin-top: 10px">
  <a href="#">
    <i class="fa fa-money"></i>
  </a>
  <span>
    <a href="#pageSubmenu4" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" style=" font-weight: bold;">Price</a>
    <ul class="collapse list-unstyled" id="pageSubmenu4">
      <li>
        <input type="radio" name="price" value="all" >All events
      </li>
      <li>
        <input type="radio" name="price" value="free" >Free
      </li>
      <li>
        <input type="radio" name="price" value="paid" >Paid
      </li>
    </ul>
  </a>
</span>
</li>
<li style="margin-top: 10px">
  <a href="#">
    <i class="fa fa-code"></i>
  </a>
  <span>
    <a href="#pageSubmenu5" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle" style="font-weight: bold;">Dev type</a>
    <ul class="collapse list-unstyled" id="pageSubmenu5">
      <li>
        <input type="radio" name="dev_type" value="all">For all developers
      </li>
      <li>
        <input type="radio" name="dev_type" value="junior" >Junior
      </li>
      <li>
        <input type="radio" name="dev_type" value="middle" >Middle
      </li>
      <li>
        <input type="radio" name="dev_type" value="experienced" >Experienced
      </li>
    </ul>
  </a>
</span>
</li>
<li>
  <%= submit "Apply Filters", phx_disable_with: "Applying...", class: "btn-sm btn btn-outline-secondary btn-lg active", style: "margin-top: 10%" %>
</form>
</li>
</ul>
</nav>
<!-- Page Content  -->
<div id="content" style="width: 100%">
  <nav>
    <div class="container-fluid" style="display: flex; flex-direction: row; align-items: baseline">
      <button type="button" id="sidebarCollapse" class="btn btn-icon btn-outline-secondary" style="margin-top: 1%">
        <i class="fa fa-align-left"></i>
      </button>
      <%= f = form_for :sorting, "#", phx_change: :events_sorting, class: "form-group", style: "margin" %>
      <%= select f, :sort_option, @sort_options, selected: @events_sort, class: "form-control form-control-sm" %>
    </form>
  </div>
</nav>